### ISSUE TITLE
Does monk supports inference by directly using pre trained models? I don't want to train the models.

### ISSUE THREAD

**Issue by shubh1608** [Tessellate-Imaging/monk_v1#105]
I have a requirement where I wanted to perform experiments on multiple pre-trained image classification models.  I was wondering if I can use monk and perform these experiments, monk seems to provide features and solve issues which I am facing.
Please note I don't want to train the models. I have created a notebook for pre-trained models available in the different libraries (Tensorflow, Keras & Pytorch).

**Comment by abhi-kumar** [comment]
By pre-trained models do you mean one trained on coco dataset?

**Comment by shubh1608** [comment]
@abhi-kumar - I mean pre-trained classification models trained on the ImageNet database.

**Comment by abhi-kumar** [comment]
Haven't enabled that feature yet, inference directly on pretrained models provided by frameworks. Will soon add it to the pipelines.

**Comment by shubh1608** [comment]
Ok, Thanks for the update @abhi-kumar.
