### ISSUE TITLE
Feature Request: Add Mish Activation

### ISSUE THREAD

**Issue by digantamisra98** [Tessellate-Imaging/monk_v1#2]
Mish is a new novel activation function proposed in - https://arxiv.org/abs/1908.08681
It has shown promising results so far and has been adopted in several packages including:

- TensorFlow Addons
- FastAI-dev
- SpaCy
- Thinc
- DarkNet

All benchmarks, analysis and links to official package implementations can be found in this repository - https://github.com/digantamisra98/Mish

It would be nice to have Mish along with both Swish and GELU activation functions.

**Comment by abhi-kumar** [comment]
Hi,

Thats a good recommendation. At present Monk supports only a certain version of pytorch, keras and mxnet. 

We are creating a community soon to discuss and implement future goals. 

We can add Mish and alike algorithms using two ways:
a) Integrate pytoch, mxnet and tensorflow's latest versions with **contrib** modules.
b) Integrate **3rd party libraries** such as https://echo-ai.readthedocs.io/en/latest/#.

Once we release the community page then we can streamline and quickly integrate the mentioned algorithms.

Thanks again for the suggestions, let us know your thoughts on the experience with the library and comments on the same.

**Comment by digantamisra98** [comment]
Hi

Thanks for the response. That sounds good, thanks for considering the proposal. Mish can be also directly integrated for TensorFlow using TensorFlow-Addons. Echo can be a good addition. We are planning to release the next set of activations and optimizers so integrating it along with Monk would be fantastic. 
I will give Monk a run this week hopefully and provide my feedback. 

Keep up the good work.
