### ISSUE TITLE
Can't install requirements_cu10.txt

### ISSUE THREAD

**Issue by nguyenanhtuan1008** [Tessellate-Imaging/monk_v1#22]
I got this error:
ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.12.0 (from -r .\installation\requirements_cu10.txt (line 12)) (from versions: 1.13.1, 1.13.2, 1.14.0, 1.15.0rc0, 1.15.0rc1, 1.15.0rc2, 1.15.0rc3, 1.15.0, 1.15.2, 2.0.0a0, 2.0.0b0, 2.0.0b1, 2.0.0rc0, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.1.0rc0, 2.1.0rc1, 2.1.0rc2,
2.1.0, 2.2.0rc0)
ERROR: No matching distribution found for tensorflow-gpu==1.12.0 (from -r .\installation\requirements_cu10.txt (line 12))

How do I install this?

**Comment by nguyenanhtuan1008** [comment]
After install python 3.6, tensorflow pass but then I got an error with PyTorch:
ERROR: Could not find a version that satisfies the requirement torch==1.2.0 (from -r .\installation\requirements_cu10.txt (line 16)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.2.0 (from -r .\installation\requirements_cu10.txt (line 16))

**Comment by abhi-kumar** [comment]
Could you please try updating your pip using this command?
pip install -U pip

And let me know if the error still persists

**Comment by THEFASHIONGEEK** [comment]
If you are using windows, remove torch==1.2.0 , torchvision==0.4.0 from requirements_cu10.txt. and run 
`pip install -r  requirements_cu10.txt`
then install pytorch using
`pip install torch===1.2.0 torchvision===0.4.0 -f https://download.pytorch.org/whl/torch_stable.html`

**Comment by abhi-kumar** [comment]
Closing the issue due to inactivity. 
And associated changes with windows have already been made.
