### ISSUE TITLE
Unit_test failed for optimizers  for gluon  cpu windows

### ISSUE THREAD

**Issue by THEFASHIONGEEK** [Tessellate-Imaging/monk_v1#32]
`Running 1/<num>
###################################################
1. Exp:         test_layer_max_pooling1d
Status:      Pass
###################################################

Total Tests           - 80
Time Taken            - 96.55078792572021 sec
Num Successful Tests  - 69
Num Failed Tests      - 11
Num Skipped Tests     - 0

1. Failed Test:
Name     - test_optimizer_sgd
Error    - 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

2. Failed Test:
Name     - test_optimizer_nesterov_sgd
Error    - 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

3. Failed Test:
Name     - test_optimizer_rmsprop
Error    - 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

4. Failed Test:
Name     - test_optimizer_momentum_rmsprop
Error    - 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

5. Failed Test:
Name     - test_optimizer_adam
Error    - 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

6. Failed Test:
Name     - test_optimizer_adamax
Error    - 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

7. Failed Test:
Name     - test_optimizer_adadelta
Error    - 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

8. Failed Test:
Name     - test_optimizer_adadelta
Error    - 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

9. Failed Test:
Name     - test_optimizer_nadam
Error    - 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

10. Failed Test:
Name     - test_optimizer_signum
Error    - 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

11. Failed Test:
Name     - test_layer_transposed_convolution3d
Error    - Error in operator conv183_deconvolution0: [00:05:17] C:\Jenkins\workspace\mxnet-tag\mxnet\src\operator\nn\deconvolution.cc:44: If not using CUDNN, only 1D or 2D Deconvolution is supported

Skipped Tests List    - []
`

**Comment by abhi-kumar** [comment]
This looks like a multi-threading issue with CPU on windows. A native pytorch error. Will search for a solution on this. 

Thanks for pointing out the issue.

**Comment by abhi-kumar** [comment]
Check these up for possible solutions
- https://github.com/dipy/dipy/issues/399
- https://github.com/dmlc/gluon-cv/issues/715

**Comment by abhi-kumar** [comment]
@THEFASHIONGEEK any updates on this issue?

**Comment by THEFASHIONGEEK** [comment]
Its resolved after changing` if __name__ == '__main__'` to ` if name == 'main'`
