### ISSUE TITLE
mxneterror: gpu is not enabled in windows_cpu

### ISSUE THREAD

**Issue by THEFASHIONGEEK** [Tessellate-Imaging/monk_v1#34]
when running 
```
gtf.Default(dataset_path="..\..\..\monk\system_check_tests\datasets\dataset_cats_dogs_train", 
            model_name="resnet18_v1", 
            num_epochs=5);
```
got this error

> mxneterror: [01:28:37] c:\jenkins\workspace\mxnet-tag\mxnet\src\ndarray\ndarray.cc:1285: gpu is not enabled.

After changing line 251 in gluon/finetune/level_14_master.py to Use_gpu=False

got this error
![image](https://user-images.githubusercontent.com/50513357/76732915-bf899e80-6785-11ea-9b0a-ab75a77a1320.png)

This is working on Keras, Pytorch backend.

**Comment by abhi-kumar** [comment]
Like in other backends if GPU isn't available it should automatically switch to CPU mode. 

This error will be resolved very soon.

**Comment by abhi-kumar** [comment]
@THEFASHIONGEEK Necessary changes have been made... Please check if this issue is resolved and it's automatically switching to CPU to not.

**Comment by abhi-kumar** [comment]
Closing the issue due to inactivity

**Comment by THEFASHIONGEEK** [comment]
yes sir issue is resolved
