### ISSUE TITLE
Dependency | Don't include all supported DL Frameworks in requirements.txt

### ISSUE THREAD

**Issue by kshitij12345** [Tessellate-Imaging/monk_v1#39]
I don't think it is a good idea to install `MXNet, Pytorch, Tensorflow` all three for using `monk`, as I am assuming, most of the people would only be using one of the framework at a given time.

The dependencies become especially heavy for GPU versions (in terms of size) as each library is heavy .

I believe it would be better for user to be able to opt-in the library/libraries of their choice.

**Comment by abhi-kumar** [comment]
Yes... Very rightly said. 

But there are two thing here
a) If you have a look at the core code, certain elements of pytorch are used in mxnet and keras backends. Even when using mxnet, pytorch has to be imported. 
b) Once tensorflow 2.0 backend is completely added, we will find a way to reduce the inter-backend dependencies and the issue with installing all the libraries will be resolved.

**Comment by kshitij12345** [comment]
Thanks for the quick response.

I haven't had a look at that part of the code. However, going forward these framework dependencies should be avoided.

Let me know if I can be of any help with the project.

**Comment by take2rohit** [comment]
I think what we can do is create a separate requirements.txt for each framework wrapper. I have also observed that the requirements.txt is extremely redundant

**Comment by abhi-kumar** [comment]
Agreed. IT will be taken care in next stable version.

**Comment by abhi-kumar** [comment]
Marked as feature enhancement, yet the solution will not be an immediate one.
