### ISSUE TITLE
Installation error for pytorch_prototype

### ISSUE THREAD

**Issue by Aakash1822** [Tessellate-Imaging/monk_v1#43]
when using
from pytorch_prototype import prototype
ModuleNotFoundError                     
<ipython-input-35-1475a4c2ff3e> in <module>()
----> 1 from pytorch_prototype import prototype

1 frames
/content/monk_v1/monk/pytorch/finetune/imports.py in <module>()
    import psutil
    import numpy as np
     import GPUtil
    def isnotebook():

ModuleNotFoundError: No module named 'GPUtil'

**Comment by abhi-kumar** [comment]
Did you follow the right installation instructions mentioned at https://github.com/Tessellate-Imaging/monk_v1/tree/master/installation?

**Comment by Aakash1822** [comment]
solved
