### ISSUE TITLE
Visualize_With_Netron not working with TensorFlow 2.x

### ISSUE THREAD

**Issue by aayush-fadia** [Tessellate-Imaging/monk_v1#44]
The problem causing line was line 303 in tf_keras_1/finetune/level_14_master_main.py
Instead of
`tf.placeholder(...)`
it should be:
`tf.keras.backend.placeholder(...)`
for TensorFlow 2.x support.

**Comment by THEFASHIONGEEK** [comment]
TensorFlow 2.0 backend is not completely added

**Comment by abhi-kumar** [comment]
As mentioned by @THEFASHIONGEEK use tf versions as per the requirement files

**Comment by abhi-kumar** [comment]
As per the suggestions made by @aayush-fadia the code is now changed to support both tf versions

Earlier code
```
 x = tf.placeholder(tf.float32, shape=(batch_size, h, w, c))
```

Update code
if(tf.__version__.split(".")[0] == "2"):
    x = tf.backend.placeholder(tf.float32, shape=(batch_size, h, w, c)) 
else:
    x = tf.placeholder(tf.float32, shape=(batch_size, h, w, c))
```

Let us know if the issue still persists

**Comment by aayush-fadia** [comment]
The issue is still there, the exact line that makes it work is:
```python
        if(tf.__version__.split(".")[0] == "2"):
            x = tf.keras.backend.placeholder(dtype=tf.float32, shape=(batch_size, h, w, c)) 
        else:
            x = tf.placeholder(tf.float32, shape=(batch_size, h, w, c))

```
For v2, it's tf.keras.backend, and the shape and dtype arguments have to be specified with keywords.

**Comment by abhi-kumar** [comment]
@aayush-fadia please make the necessary changes and raise a PR

**Comment by aayush-fadia** [comment]
Done
PR: https://github.com/Tessellate-Imaging/monk_v1/pull/61
