### ISSUE TITLE
Index out of range when using GPU on Kaggle

### ISSUE THREAD

**Issue by arijitgupta42** [Tessellate-Imaging/monk_v1#47]
I am running monk on a Kaggle notebook with mxnet backend, and when I am running my model on the GPU, after the first two iterations I'm getting a list index out of range error.
```
/kaggle/working/monk_v1/monk/gluon/finetune/level_3_training_base.py in set_training_final(self)
    332                 if(self.system_dict["model"]["params"]["use_gpu"]):
    333                     GPUs = GPUtil.getGPUs()
--> 334                     gpuMemoryUsed = GPUs[0].memoryUsed
    335                     if(self.system_dict["training"]["outputs"]["max_gpu_memory_usage"] < int(gpuMemoryUsed)):
    336                         self.system_dict["training"]["outputs"]["max_gpu_memory_usage"] = int(gpuMemoryUsed);

IndexError: list index out of range
```

**Comment by abhi-kumar** [comment]
Will add a solution that temporarily ignores GPU util when on kaggle, till kaggle solves it's native errors related to nvidia-smi command

**Comment by abhi-kumar** [comment]
I have added a temporary solution. This will keep the gpu usage statistics as always Null on kaggle yet utilize GPUs.

Please check and let us know if the issue is resolved.

**Comment by abhi-kumar** [comment]
If the main issue on kaggle is not resolved, we will make a permanent fix using try catch exceptions

**Comment by arijitgupta42** [comment]
> I have added a temporary solution. This will keep the gpu usage statistics as always Null on kaggle yet utilize GPUs.
> 
> Please check and let us know if the issue is resolved.

The issue seems to be resolved now
