### ISSUE TITLE
ptf.Reload() is not working sometimes

### ISSUE THREAD

**Issue by mahakkothari** [Tessellate-Imaging/monk_v1#54]
after updating, when we do ptf.Reload() it gives some error saying "name 'self' is not defined"
![WhatsApp Image 2020-03-31 at 1 22 24 PM](https://user-images.githubusercontent.com/44318481/78001524-6c9e1280-7353-11ea-8cef-b100c8f1d368.jpeg)

**Comment by THEFASHIONGEEK** [comment]
Download the latest version of monk. The issue will be resolved.

**Comment by mahakkothari** [comment]
ok
