### ISSUE TITLE
Issue when giving data to model

### ISSUE THREAD

**Issue by shubham7169** [Tessellate-Imaging/monk_v1#58]
![Capture](https://user-images.githubusercontent.com/62787268/78790534-4c61f980-79cc-11ea-8c30-91bad5e75c92.PNG)
Getting this error when giving data to model.

**Comment by abhi-kumar** [comment]
Can you please specify more details. And attach the csv file raising this issue?

**Comment by abhi-kumar** [comment]
Solution has been added. Please check and let us know if error still persists

**Comment by shubham7169** [comment]
Thank you sir, error still persists.
![Capture](https://user-images.githubusercontent.com/62787268/78867584-f38f7100-7a5e-11ea-8d76-7fdf4c66147a.PNG)

**Comment by abhi-kumar** [comment]
Please check now

**Comment by shubham7169** [comment]
Now working

**Comment by shubham7169** [comment]
Now gtf.Train() is giving error.
![Capture](https://user-images.githubusercontent.com/62787268/78884412-7e309a00-7a78-11ea-9055-351443ec803c.PNG)

**Comment by abhi-kumar** [comment]
can you please check if the training csv has labels as string or integers?

**Comment by sinchubhat** [comment]
all strings, i converted the integer to string

**Comment by abhi-kumar** [comment]
@shubham7169 while saving the csv using pandas make sure you set "index" argument as False

And the rest of the errors are now resolved... No need to change int to string. It will automatically get converted now. 

Since all the classes were numpy integers they were not being saved as json

**Comment by shubham7169** [comment]
Ok
