### ISSUE TITLE
Type Error: Object of type 'int64' is not JSON serializable

### ISSUE THREAD

**Issue by sinchubhat** [Tessellate-Imaging/monk_v1#59]
![image](https://user-images.githubusercontent.com/32384381/78886790-6a873280-7a7c-11ea-8680-37157fc29512.png)

**Comment by abhi-kumar** [comment]
Its now resolved... No need to change int to string. It will automatically get converted now. 

Since all the classes were numpy integers they were not being saved as json

**Comment by sinchubhat** [comment]
Yes it works fine now
