### ISSUE TITLE
AttributeError: 'numpy.int64' object has no attribute 'split'

### ISSUE THREAD

**Issue by sinchubhat** [Tessellate-Imaging/monk_v1#62]
![image](https://user-images.githubusercontent.com/32384381/79017852-f3db5980-7b8f-11ea-8893-26afc9172796.png)

**Comment by THEFASHIONGEEK** [comment]
Ya I resoloved this error by changing line 89 to if(len(df[columns[-1]][i].split(" ")) > 1)

**Comment by THEFASHIONGEEK** [comment]
I think changing line 89  in pytorch/datasets/paths.py to 
`if type(df[columns[1]][i])==str & len(df[columns[-1]][i].split(" ")) > 1:`
 will resolve the issue

**Comment by abhi-kumar** [comment]
@sinchubhat and @THEFASHIONGEEK please check if the above mentioned solution resolved the issue or not

**Comment by sinchubhat** [comment]
Yes it works properly now
