### ISSUE TITLE
ValueError: too many values to unpack 

### ISSUE THREAD

**Issue by sinchubhat** [Tessellate-Imaging/monk_v1#65]
![image](https://user-images.githubusercontent.com/32384381/79047827-c1386c00-7c36-11ea-8755-ae6508b976a3.png)
![image](https://user-images.githubusercontent.com/32384381/79047837-d614ff80-7c36-11ea-861b-20847cdf19b6.png)

**Comment by abhi-kumar** [comment]
Check if the csv file has more than two columns

**Comment by sinchubhat** [comment]
Yes i changed
