### ISSUE TITLE
AttributeError: 'function' object has no attribute 'function'

### ISSUE THREAD

**Issue by sinchubhat** [Tessellate-Imaging/monk_v1#69]
![image](https://user-images.githubusercontent.com/32384381/80960829-46263800-8e27-11ea-9218-abf476333e82.png)

**Comment by abhi-kumar** [comment]
This error will be removed soon. We are trying to speed up the imports. And this bug is being resolved now.

**Comment by abhi-kumar** [comment]
Please check if it's resolved now and monk is up and running with faster loading

**Comment by sinchubhat** [comment]
yes , it works properly now
