### ISSUE TITLE
TypeError: img should be PIL Image. Got <class 'torch.Tensor'>

### ISSUE THREAD

**Issue by sinchubhat** [Tessellate-Imaging/monk_v1#70]
![image](https://user-images.githubusercontent.com/32384381/81189650-74954600-8fd4-11ea-94ed-cba4df10ef27.png)
![image](https://user-images.githubusercontent.com/32384381/81189703-837bf880-8fd4-11ea-83e0-ff5aca4399f2.png)
![image](https://user-images.githubusercontent.com/32384381/81189766-968ec880-8fd4-11ea-9517-9a91e7bd7d6a.png)
![image](https://user-images.githubusercontent.com/32384381/81189792-a1495d80-8fd4-11ea-94aa-48ac63084e2c.png)

**Comment by abhi-kumar** [comment]
Calling the Default function multiple times appends multiple transforms and thus the error. Always call Default function with prototype function where you are creating experiment and project
