### ISSUE TITLE
Errors while using pytorch backend 

### ISSUE THREAD

**Issue by sinchubhat** [Tessellate-Imaging/monk_v1#72]
https://www.kaggle.com/sinchubhat/covid19-analysis-using-monk

i am working on this dataset 
1 when i use inception_v3 model
gtf.Default(dataset_path="/kaggle/input/covid19-image-dataset/Covid19-dataset/train", 
            model_name="inception_v3", 
            num_epochs=10);
Its not loading pretrained model even after restarting the notebook and running them again
![image](https://user-images.githubusercontent.com/32384381/81478873-9e9d7100-923d-11ea-9393-59434a21757d.png)

2. when i tried resnet152 model , it did load the pretrained model,but while running gtf.train()
it showed AttributeError: 'JpegImageFile' object has no attribute 'getexif' error 
![image](https://user-images.githubusercontent.com/32384381/81478894-c5f43e00-923d-11ea-8c48-1728e5be8caa.png)

**Comment by sinchubhat** [comment]
i even tried with keras backend , model = inception_v3 , 
here its loading the pretrained model, but when i run gtf.train()
it shows AttributeError: 'JpegImageFile' object has no attribute 'getexif' error

**Comment by sinchubhat** [comment]
with mxnet-gluon backend and resnet101_v1 model there are no errors at all

**Comment by sinchubhat** [comment]
even keras backend with densenet201 model worked without any error

**Comment by abhi-kumar** [comment]
1) While using pillow==5.4.1, pytorch backend and resnet152 model I wasn't able to reproduce this error "AttributeError: 'JpegImageFile' object has no attribute 'getexif' error"  (trained for 100 epochs). Please try again and check with the mentioned pillow version. 

2) With same pillow version (5.4.1), keras backend and inception_v2 model, again  I wasn't able to reproduce this error "AttributeError: 'JpegImageFile' object has no attribute 'getexif' error" (trained for 100 epochs) . Please try again and check with the mentioned pillow version. 

3) The issue of inception v3 is native torchvision one, the model server could possibly be down.

**Comment by sinchubhat** [comment]
So in the requirements.txt , pillow version can b changed from pillow==6.0.0 to pillow==5.4.1 to avoid the errors.

**Comment by abhi-kumar** [comment]
Yes, that can be done. Please raise a PR with the required changes

**Comment by abhi-kumar** [comment]
Does the pillow version 5.4.1 remove the error?

**Comment by sinchubhat** [comment]
yes
