### ISSUE TITLE
experiment_state.json file undetected

### ISSUE THREAD

**Issue by bosecodes** [Tessellate-Imaging/monk_v1#75]
**Steps to reproduce:**

- Running a model from the model zoo
- And performing self-training in real time
- Using Keras Backend for prototyping
- Create project and experiment

Syntax:
```
gtf.Default(dataset_path="the-simpsons-characters-dataset/train",
            model_name="alexnet", 
            freeze_base_network=False,
            num_epochs=2);
```

**Expected Behaviour:**
The model should implement without compilation errors, with the _experiment_state.json_ file detected.

Error:
```
Dataset Details
    Train path:     the-simpsons-characters-dataset/train
    Val path:       None
    CSV train path: None
    CSV val path:   None
    Label Type:     single

Dataset Params
    Input Size:   224
    Batch Size:   4
    Data Shuffle: True
    Processors:   8
    Train-val split:   0.7

Found 29327 images belonging to 43 classes.
Found 12539 images belonging to 43 classes.
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-46-d99f83683376> in <module>
      2             model_name="alexnet",
      3             freeze_base_network=False,
----> 4             num_epochs=2);

./monk/system/imports.py in decorator_wrapper(*function_args, **function_args_dicts)

./monk/system/imports.py in decorator_wrapper(*function_args, **function_args_dicts)

./monk/system/imports.py in decorator_wrapper(*function_args, **function_args_dicts)

./monk/keras_prototype.py in Default(self, dataset_path, path_to_csv, delimiter, model_name, freeze_base_network, num_epochs)

./monk/system/imports.py in decorator_wrapper(*function_args, **function_args_dicts)

./monk/tf_keras_1/finetune/level_14_master_main.py in Dataset(self)

./monk/system/imports.py in decorator_wrapper(*function_args, **function_args_dicts)

./monk/system/common.py in save(system_dict)

./monk/system/imports.py in decorator_wrapper(*function_args, **function_args_dicts)

./monk/system/common.py in write_json(system_dict)

FileNotFoundError: [Errno 2] No such file or directory: 'workspace/Project-Anime/Mxnet-alexnet//experiment_state.json'

```

**Comment by THEFASHIONGEEK** [comment]
Hi,

Before running gft.default  you need to Provide project name, Provide experiment name.

For example 
`gtf.Prototype("sample-project-1", "sample-experiment-1");`

For more details check out [link](https://github.com/Tessellate-Imaging/monk_v1/tree/master/study_roadmaps/1_getting_started_roadmap/1_getting_started_with_monk)

If the issue still persists, please let us know.

Thanks

**Comment by bosecodes** [comment]
> Hi,
> 
> Before running gft.default you need to Provide project name, Provide experiment name.
> 
> For example
> `gtf.Prototype("sample-project-1", "sample-experiment-1");`
> 
> For more details check out [link](https://github.com/Tessellate-Imaging/monk_v1/tree/master/study_roadmaps/1_getting_started_roadmap/1_getting_started_with_monk)
> 
> If the issue still persists, please let us know.
> 
> Thanks

Hey, I had already done the same, it still doesn't seem to work

**Comment by abhi-kumar** [comment]
Could you please check if you have write access in the working directory. And also check is workspace folder is created when you execute the command 
```
gtf.Prototype("sample-project-1", "sample-experiment-1");
```

At times re-running the entire code helps, and make sure you are using python 3.6; python 3. is causing some issues.

**Comment by bosecodes** [comment]
> Could you please check if you have write access in the working directory. And also check is workspace folder is created when you execute the command
> 
> ```
> gtf.Prototype("sample-project-1", "sample-experiment-1");
> ```
> 
> At times re-running the entire code helps, and make sure you are using python 3.6; python 3. is causing some issues.

The working directory is infact created, I can even see the JSON while browsing. I knew the issue with 3.7 and therefore used 3.6, still it's giving issues

**Comment by abhi-kumar** [comment]
Please share the entire code, I will check it up here and resolve it asap.

**Comment by bosecodes** [comment]
```
# Monk
import os
import sys
sys.path.append("monk_v1/monk/");
# For Keras backend
from keras_prototype import prototype
# Create Project and Experiment

gtf = prototype(verbose=1);
gtf.Prototype("Project-Anime", "Mxnet-alexnet");

os.chdir('..')
os.chdir('./study_roadmaps/4_image_classification_zoo/')
gtf.Default(dataset_path="the-simpsons-characters-dataset/train",
            model_name="alexnet", 
            freeze_base_network=False,
            num_epochs=2);
```

The last line of the code is what gives the above error

**Comment by abhi-kumar** [comment]
This is causing the issue. 

```
os.chdir('..')
os.chdir('./study_roadmaps/4_image_classification_zoo/')
```

The working directory for 
```
gtf = prototype(verbose=1);
gtf.Prototype("Project-Anime", "Mxnet-alexnet");
```

should be same for 

```
gtf.Default(dataset_path="the-simpsons-characters-dataset/train",
            model_name="alexnet", 
            freeze_base_network=False,
            num_epochs=2);
```

Hence, the workspace and experiment_json is not being found.

**Comment by bosecodes** [comment]
I just readjusted the directory tree and it seems to be working fine. Probably that was the source of the problem. Thanks :)
