### ISSUE TITLE
KeyError: 'train' for a dataset which doesn't have train folder, how to split?

### ISSUE THREAD

**Issue by vidyap-xgboost** [Tessellate-Imaging/monk_v1#85]
I've gone through tutorials for updating `hyper parameters`, especially this https://github.com/Tessellate-Imaging/monk_v1/blob/master/study_roadmaps/1_getting_started_roadmap/5_update_hyperparams/2_data_params/4)%20Play%20around%20with%20train-val%20splits.ipynb to split my dataset into train and validation. But I couldn't get anything like that so I took this [Classifier](https://github.com/Tessellate-Imaging/monk_v1/blob/f76ad2d00b4e61b245290675180698d28a20769e/study_roadmaps/4_image_classification_zoo/Classifier%20-%20Apparel%20images%20dataset.ipynb) to start training my classifier from scratch.

When I run the below code:

```python
gtf.Default(dataset_path="/content/drive/My Drive/Data/zalando/zalando",
            model_name="resnet152_v2", 
            freeze_base_network=True,
            num_epochs=2)
```
**I keep getting this error**.

```python
Dataset Details
    Train path:     /content/drive/My Drive/Data/zalando/zalando
    Val path:       None
    CSV train path: None
    CSV val path:   None
    Label Type:     single

Dataset Params
    Input Size:   224
    Batch Size:   4
    Data Shuffle: True
    Processors:   2
    Train-val split:   0.7

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-10-ca95f2c1dd79> in <module>()
      2             model_name="resnet152_v2",
      3             freeze_base_network=True,
----> 4             num_epochs=2)

9 frames
/content/monk_v1/monk/gluon/finetune/level_1_dataset_base.py in set_dataset_dataloader(self, test)
    116 
    117 
--> 118                 self.system_dict["dataset"]["params"]["num_train_images"] = len(image_datasets["train"]);
    119                 self.system_dict["dataset"]["params"]["num_val_images"] = len(image_datasets["val"]);
    120 

KeyError: 'train'
```

**Where did I go wrong?**

Environment: Google Colab

**Comment by vidyap-xgboost** [comment]
Surprisingly, this didn't happen when I first ran the code, it happened only when I factory reset the runtime, this started happening.

**Comment by abhi-kumar** [comment]
Thank you for the detailed analysis on debugging the error
